Missing return!
I'm stopping here though, the next error is base/plasma/ions/willab/ion_willab.cpp:120: error: 'Celsius' is not a member of 'WeatherUtils'

svn path=/trunk/playground/base/plasma/MediaCenterComponents/; revision=1098124